## Descriptive statistics

In [1]:
import numpy as np

In [2]:
x = np.array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
                2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [3]:
len(x)

26

In [5]:
np.mean(x)

4.8076923076923075

In [6]:
np.var(x)

115.23224852071006

In [7]:
np.std(x)

10.734628476137871

In [9]:
np.max(x)

23

In [10]:
np.min(x)

-24

In [11]:
np.median(x)

5.0

In [12]:
np.percentile(x, 0)

-24.0

In [13]:
np.percentile(x, 25)

0.0

In [14]:
np.percentile(x, 50)

5.0

In [15]:
np.percentile(x, 75)

10.0

In [16]:
np.percentile(x, 100)

23.0

In [17]:
from scipy.stats import describe

In [18]:
describe(x)

DescribeResult(nobs=26, minmax=(-24, 23), mean=4.8076923076923075, variance=119.84153846153846, skewness=-0.4762339485461929, kurtosis=0.37443381660038977)

In [19]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [20]:
x

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [21]:
y

array([10001, 10002, 10003, ..., 19998, 19999, 20000])

In [22]:
z = np.zeros_like(x)

In [23]:
for i in range(10000) :
    z[i] = x[i] + y[i]

In [25]:
z[:50]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020, 10022, 10024, 10026, 10028, 10030, 10032, 10034, 10036,
       10038, 10040, 10042, 10044, 10046, 10048, 10050, 10052, 10054,
       10056, 10058, 10060, 10062, 10064, 10066, 10068, 10070, 10072,
       10074, 10076, 10078, 10080, 10082, 10084, 10086, 10088, 10090,
       10092, 10094, 10096, 10098, 10100])

In [26]:
z = x + y

In [27]:
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [29]:
a = np.array([1,5,3,3])
b = np.array([2,3,3,5])

In [30]:
a==b

array([False, False,  True, False], dtype=bool)

In [31]:
a>=b

array([False,  True,  True, False], dtype=bool)

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [34]:
np.all(a==b)

False

In [36]:
np.all(a==c)

True

In [37]:
a = np.arange(5)

In [38]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [39]:
10**a

array([    1,    10,   100,  1000, 10000])

In [40]:
np.log(a+2)

array([ 0.69314718,  1.09861229,  1.38629436,  1.60943791,  1.79175947])

In [41]:
x = np.arange(10)

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [44]:
x=np.arange(12).reshape(3,4)

In [45]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
x=100*x

In [48]:
x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [49]:
x = np.arange(6)

In [50]:
y = np.ones_like(x)

In [51]:
x+y

array([1, 2, 3, 4, 5, 6])

In [52]:
x+1

array([1, 2, 3, 4, 5, 6])

In [55]:
x= np.vstack([range(7)[i:i+3] for i in range(5)])

In [56]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [57]:
y = np.arange(5)[: , np.newaxis]

In [58]:
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [59]:
x+y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [60]:
y = np.arange(3)

In [61]:
x+y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [62]:
x=np.arange(5)

In [63]:
x

array([0, 1, 2, 3, 4])

In [64]:
np.sum(x)

10

In [65]:
x.sum()

10

In [66]:
x.argmin()

0

In [67]:
x.argmax()

4

In [69]:
x = np.array([[1,1], [2,2]])

In [70]:
x

array([[1, 1],
       [2, 2]])

In [71]:
x.sum()

6

In [72]:
x.sum(axis=0)

array([3, 3])

In [73]:
x.sum(axis=1)

array([2, 4])

연습 문제 1¶  
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.  

전체의 최댓값  
각 행의 합  
각 열의 평균  

In [82]:
x = np.random.randint(50, size = 30)

In [89]:
x = x.reshape(5,6)

In [93]:
x

array([[48, 34, 33,  2, 34, 46],
       [41, 34, 29,  1, 19, 21],
       [35, 45, 19, 15, 29, 22],
       [37, 16, 26, 43, 10, 29],
       [ 1, 35, 10, 31, 16, 10]])

In [90]:
x.max()

48

In [91]:
x.sum(axis=1)

array([197, 145, 165, 161, 103])

In [92]:
x.mean(axis=0)

array([ 32.4,  32.8,  23.4,  18.4,  21.6,  25.6])

In [97]:
a = np.random.randint(30 , size = 12)

In [98]:
a = a.reshape(3,4)

In [99]:
a

array([[ 3, 27, 21, 25],
       [ 9, 11, 17, 10],
       [ 3,  5, 21,  5]])

In [100]:
np.sort(a)

array([[ 3, 21, 25, 27],
       [ 9, 10, 11, 17],
       [ 3,  5,  5, 21]])

In [101]:
np.sort(a, axis=0)

array([[ 3,  5, 17,  5],
       [ 3, 11, 21, 10],
       [ 9, 27, 21, 25]])

In [102]:
a.sort(axis=0)

In [103]:
a

array([[ 3,  5, 17,  5],
       [ 3, 11, 21, 10],
       [ 9, 27, 21, 25]])

In [104]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [105]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [107]:
index

array(['a', 'b', 'c'],
      dtype='<U1')

In [108]:
count

array([2, 2, 1])

In [109]:
np.bincount([1,1,3,2,4,5], minlength=6)

array([0, 2, 1, 1, 1, 1])

## pandas

In [110]:
import pandas as pd

In [111]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [112]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [113]:
s.values

array([9904312, 3448737, 2890451, 2466052])

In [115]:
s.name = 'population'

In [116]:
s.index.name = 'city'
s

city
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: population, dtype: int64

In [118]:
s/1000000

city
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: population, dtype: float64

In [121]:
s[1] == s['부산']

True

In [123]:
s[[0,2]]

city
서울    9904312
인천    2890451
Name: population, dtype: int64

In [124]:
s[['서울', '대구', '부산']]

city
서울    9904312
대구    2466052
부산    3448737
Name: population, dtype: int64

In [127]:
s[(2500004 < s) & (s < 5000004)]

city
부산    3448737
인천    2890451
Name: population, dtype: int64

In [126]:
s[(250e4 < s) & (s < 500e4)]

city
부산    3448737
인천    2890451
Name: population, dtype: int64

In [129]:
s

city
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: population, dtype: int64

In [130]:
s[1:2+1]

city
부산    3448737
인천    2890451
Name: population, dtype: int64

In [131]:
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [132]:
s0.a

0

In [133]:
s0.b

1

In [134]:
'서울' in s

True

In [138]:
for k, v in s.items():
    print('%s = %d'% (k, v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [139]:
for k, v in s.items() :
    print('%s : %d' % (k,v))

서울 : 9904312
부산 : 3448737
인천 : 2890451
대구 : 2466052


In [140]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

대전    1490158
부산    3393191
서울    9631482
인천    2632035
dtype: int64

In [142]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}, index = ['서울', '부산', '인천', '대전'])


In [144]:
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [145]:
ds = s - s2

In [146]:
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [147]:
s.values - s2.values

array([272830,  55546, 258416, 975894])

In [148]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [149]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [153]:
rs = (s-s2)/s2 *100

In [154]:
rs

대구         NaN
대전         NaN
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

In [157]:
rs['부산']=1.63

In [158]:
rs

대구         NaN
대전         NaN
부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [164]:
rs['서울'] = 2.8

In [165]:
rs

대구        NaN
대전        NaN
부산       1.63
인천    9.81811
서울        2.8
dtype: object

연습 문제 1¶  
임의로 두 개의 시리즈 객체를 만든다. 모두 문자열 인덱스를 가져야 하며 두 시리즈에 공통적으로 포함되지 않는 라벨이 있어야 한다.  
위에서 만든 두 시리즈 객체를 이용하여 사칙 연산을 한다.  

In [169]:
a_grades = pd.Series([66,98,89,78,77], index = ['lee', 'park', 'shin', 'jung', 'song' ])

In [170]:
b_grades = pd.Series([63,89,56,99,87], index = ['yi', 'ryu', 'ju', 'ma', 'yang' ])

In [177]:
a_grades.values + b_grades.values

array([129, 187, 145, 177, 164])

In [178]:
a_grades.values * b_grades.values

array([4158, 8722, 4984, 7722, 6699])

In [179]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [180]:
df.index.name = 'city'
df.columns.name = 'feature'

In [181]:
df

feature   지역     2015     2010     2005     2000  2010-2015 증가율
city                                                           
서울       수도권  9904312  9631482  9762546  9853972         0.0283
부산       경상권  3448737  3393191  3512547  3655437         0.0163
인천       수도권  2890451  2632035  2517680  2466338         0.0982
대구       경상권  2466052  2431774  2456016  2473990         0.0141

연습 문제 2¶  
다음 조건을 만족하는 임의의 데이터프레임을 하나 만든다. 

열의 갯수와 행의 갯수가 각각 5개 이상이어야 한다.  
열에는 정수, 문자열, 실수 자료형 데이터가 각각 1개 이상씩 포함되어 있어야 한다.  

In [188]:
data_ = {
    'lee' : [4.5, 4, 3, 4.5, 4],
    'park' : [3, 4, 3.5, 4, 3.5],
    'jung' : [3, 3, 2.5, 3.5, 4],
    'jason': [4.5, 4, 4.5, 4.5, 4],
    'yu' : [4, 4, 4, 3.5, 4],
    'lecture' : ['BDM', 'EC', 'CS', 'BE', 'DS']
}
columns = ['lee', 'park', 'jung', 'jason', 'yu']
index = ['BDM', 'EC', 'CS', 'BE', 'DS']

dataframe = pd.DataFrame(data_, index= index, columns=columns)

In [189]:
dataframe

lee  park  jung  jason   yu
BDM  4.5   3.0   3.0    4.5  4.0
EC   4.0   4.0   3.0    4.0  4.0
CS   3.0   3.5   2.5    4.5  4.0
BE   4.5   4.0   3.5    4.5  3.5
DS   4.0   3.5   4.0    4.0  4.0

In [190]:
df

feature   지역     2015     2010     2005     2000  2010-2015 증가율
city                                                           
서울       수도권  9904312  9631482  9762546  9853972         0.0283
부산       경상권  3448737  3393191  3512547  3655437         0.0163
인천       수도권  2890451  2632035  2517680  2466338         0.0982
대구       경상권  2466052  2431774  2456016  2473990         0.0141

In [191]:
df["2010-2015 증가율*100"] = df["2010-2015 증가율"] * 100
df

feature   지역     2015     2010     2005     2000  2010-2015 증가율  \
city                                                              
서울       수도권  9904312  9631482  9762546  9853972         0.0283   
부산       경상권  3448737  3393191  3512547  3655437         0.0163   
인천       수도권  2890451  2632035  2517680  2466338         0.0982   
대구       경상권  2466052  2431774  2456016  2473990         0.0141   

feature  2010-2015 증가율*100  
city                        
서울                    2.83  
부산                    1.63  
인천                    9.82  
대구                    1.41

In [192]:
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

feature   지역     2015     2010     2005     2000  2010-2015 증가율  \
city                                                              
서울       수도권  9904312  9631482  9762546  9853972         0.0283   
부산       경상권  3448737  3393191  3512547  3655437         0.0163   
인천       수도권  2890451  2632035  2517680  2466338         0.0982   
대구       경상권  2466052  2431774  2456016  2473990         0.0141   

feature  2010-2015 증가율*100  2005-2010 증가율  
city                                       
서울                    2.83          -1.34  
부산                    1.63          -3.40  
인천                    9.82           4.54  
대구                    1.41          -0.99

연습 문제 3¶  
다음 데이터프레임에서 지정하는 데이터를 뽑아내거나 처리하라.  

data = {  
    "국어": [80, 90, 70, 30],  
    "영어": [90, 70, 60, 40],  
    "수학": [90, 60, 80, 70],  
}  
columns = ["국어", "영어", "수학"]  
index = ["춘향", "몽룡", "향단", "방자"]  
df = pd.DataFrame(data, index=index, columns=columns)  
1.모든 학생의 수학 점수를 시리즈로 나타낸다.  
2.모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.  
3.모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.  
4.방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.  
5.춘향의 점수를 데이터프레임으로 나타낸다.  
6.향단의 점수를 시리즈로 나타낸다.  

In [229]:
data = {
"국어": [80, 90, 70, 30],
"영어": [90, 70, 60, 40],
"수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [194]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [209]:
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [210]:
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [230]:
df['avg'] = ((df['국어']+df['영어']+df['수학'])/3).round(2)

In [231]:
df

국어  영어  수학    avg
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [227]:
#4.방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
df['영어']['방자'] = 80
df['avg'] = ((df['국어']+df['영어']+df['수학'])/3).round(2)

/Users/sanghyub/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [228]:
df

국어  영어  수학    avg
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  60.00

In [252]:
#5.춘향의 점수를 데이터프레임으로 나타낸다.
df[:1]

국어  영어  수학    avg
춘향  80  90  90  86.67

In [257]:
#6.향단의 점수를 시리즈로 나타낸다.
df2 = df.T

In [258]:
df2['향단']

국어     70.0
영어     60.0
수학     80.0
avg    70.0
Name: 향단, dtype: float64