## Bayesian Probability

#### Probability of group A's CVR is higher that of group B's  
: $P(A>B)$

#### Probability of group B's CVR is higher than that of group A's  
: $P(B>A)$

$a : \text{Conversion rate of A}$  
$b : \text{Conversion rate of B}$ 

$$P(A>B)=\int_{a=0}^{1}\int_{b=0}^{a} P(a|A) * P(b|B)$$ 

### 간단한 테스트 상황에서는 잘 동작하지만 실전에서 사용할 때 두 가지 문제가 있다. 
- 첫째, 전환율을 계산할 때 시행 횟수와 전환 횟수가 매우 큰 경우에는 "함수가 정확한 적분값을 계산하지 못한다. 이것은 정밀도 문제 때문에 생기는 현상인데 가령 아래와 같은 경우는 엉뚱한 값을 출력한다. 
 
 
- 또 다른 문제점은 정량값 확률을 계산하는  만약 확률을 계산할 그룹의 정량값의 분포가 정규분포와 크게 다르다면(예를 들어 멱함수 분포) 확률이 부정확하게 계산될 수 있다. 이 문제를 해결하려면 해당 그룹의 데이터 분포에 맞게 dnorm과 pnorm 함수 호출 부분을 수정해줘야 한다. 특히 만약 데이터의 분포가 모수적 방법으로 표현할 수 없는 분포라면 비모수적 기법(non-parametric method)을 이용해 확률 분포를 계산해 줘야 한다.

### In R code
- 접두사	의미
    - d : 확률 밀도(질량) 함수 (probability density/mass function)
    - p : 누적 분포 함수 (cumulative distribution function)
    - q : 분위수 계산 함수 (quantile function)
    - r : 랜덤 샘플 생성 (sample realization)
    


``` R
bayesian.stat.for.rate<-function(data){
  k <- nrow(data)
  result<-numeric(k)
  for(i in (1:k)){
    idx<-(1:k)[-i]
    f<-function(z){  # z는 분위수(매개변수)
      r<-dbeta(z,
               data[i, 'conversion']+1, # alpha
               data[i, 'trial'] - data[i, 'conversion'] + 1) # beta
      for (j in idx){
        r<-r*pbeta(z,
                   data[j, 'conversion'] + 1,
                   data[j, 'trial'] - data[j, 'conversion'] + 1)
      }
      return(r) # Likelihood Distribution
    }
    result[i] = integrate(f, 0,1)$value  # Integral of Likelihood
    }
  return(result) # Probability
}
``` 

In [11]:
import scipy.integrate as integrate
import scipy.special as special
from scipy import integrate
from scipy.stats import beta
import numpy as np
import pandas as pd

$P(a|A)$ 적분 후, $P(b|B)$

``` R
prob.a.better.b <- integrate(function(x) {
    dbeta(x, ca+1, ta-ca+1) * pbeta(x, cb+1, ta-cb-+1)
    },0,1)
```

In [13]:
data = {'group' : ['A','B','C'],
       'trial' : [8500, 8500, 8500],
       'conversion' : [1500, 1410, 1420]}

In [14]:
df_data = pd.DataFrame(data)

In [18]:
basic_data

group  trial  conversion
0     A   8500        1500
1     B   8500        1410

In [17]:
basic_data = df_data.iloc[:2]

### Basian Probability $P(A>B)$ 구현 코드

96.79%

In [217]:
res = integrate.quad(lambda x: beta.pdf(x, 1500+1, 8500-1500+1)*
               beta.cdf(x, 1410+1, 8500-1410+1),0,1)

In [218]:
res[0]

0.966554243344272

In [219]:
1-res[0]

0.03344575665572802

3.21%

In [220]:
integrate.quad(lambda x: beta.pdf(x, 1410+1, 8500-1410+1)*
               beta.cdf(x, 1500+1, 8500-1500+1),0,1)

(0.03344575665791428, 5.450926853986515e-10)

In [31]:
lambda x: beta.pdf(x, 1500+1, 8500-1500+1)*\
               beta.cdf(x, 1410+1, 8500-1410+1)

<function __main__.<lambda>(x)>

In [38]:
basic_data.iloc[0,1]

8500

In [32]:
len(basic_data)

2

In [37]:
k=3
for i in range(0,k):
    lst = list(range(0,k))
    set_lst = set(lst)
    index = list(set_lst-{i})
    print(i)
    print('index', index)

0
index [1, 2]
1
index [0, 2]
2
index [0, 1]


$${\rm Pr}(p_C > \max\{p_A, p_B\}) = \\ 1 - {\rm Pr}(p_A > p_C) - {\rm Pr}(p_B > p_C)
+ \sum_{i=0}^{\alpha_A-1} \sum_{j=0}^{\alpha_B-1}{\frac{B(i+j+\alpha_C, \beta_A + \beta_B + \beta_C)}{(\beta_A+i)B(1+i,\beta_A)(\beta_B+j)B(1+j,\beta_B)B(\alpha_C, \beta_C)}}$$

In [88]:
import numpy as np

In [99]:
result = np.array([0,1,2])
result[2] = 3
result[2]

3

In [108]:
#A/B/C라면 P(A>B), P(B>C), P(A>C)를 다 구해야함
result = np.array([0,0,0])
def bayesian_stat_for_rate(data):

    k = len(data)
#     print(k)
    for i in range(0,k):
        print(i)
        lst = list(range(0,k,1))
        set_lst = set(lst)
        index = list(set_lst-{i})

#         #가능도 함수 구하는 함수
#         lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
#                                data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
#                              data.iloc[j,2]+1)
#         print(lst)
        for j in index:
            result[i] = integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
                                   data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
                                 data.iloc[j,2]+1),0,1)[0]
            print(integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
                                   data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
                                 data.iloc[j,2]+1),0,1)[0])
    
    return result


    #가능도 함수 f를 구해서 정의역 구간에서 integrate 하자 ==> likelihood의 적분 == 확률
#     result[i] = integrate.quad(funtion, 0,1)[0]
        
#     return result

## test code

- i가 1일때 j는 2에서 r값을 구하고, 3에서 구한 r값을 업데이트한다. 이 값을 가진 함수를 integrate해주면 result[0]번의 값이 생성된다.  
- 같은 방식으로 i가 2일때 j는 1과 3번째 row의 값을 이용해서 r값을 업데이트 하고 이 값을 가진 함수를 integrate해서 result[1]번의 값을 만들어 낸다.

In [156]:
basic_data.iloc[1,2]

1410

### 매개변수 z 구현 및 r 값 세팅
- z 그냥 사용하고 r에 업데이트를 할까?
- z가 고정되어 있는데... 값이 제대로 나올까?

z=0.500000000 0.013046736 0.986953264 0.067468317 0.932531683 0.160295216 0.839704784 0.283302303 0.716697697 0.425562831 0.574437169
0.002171418 0.997828582 0.034921254 0.965078746 0.109591137 0.890408863 0.218621433 0.781378567 0.352803569 0.647196431

In [193]:
z = np.linspace(beta.pdf(0.01, 0, 1),beta.pdf(0.99, 0.1, 1), 21)
z

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       0.10090863])

In [257]:
integrate.quad(lambda x: beta.pdf(x, 1500+1, 8500-1500+1)*
               beta.cdf(x, 1410+1, 8500-1410+1),0,1)

(0.966554243344272, 2.7706948534619212e-09)

In [279]:
def func(data, z,i,j):
    return func_pdf(data, z,i,j)*func_cdf(data, z,i,j)


In [280]:
func(basic_data,z,0,1)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       2.72596719e-277, 1.62454722e-206, 1.53771005e-149, 4.22507788e-104,
       1.74980338e-068, 2.34786376e-041, 1.16671866e-021, 1.56586123e-008,
       3.14739997e-001, 5.82779318e+001, 1.99007472e+000, 2.51200029e-004,
       2.55689318e-010, 2.90434473e-018, 4.84465911e-028, 1.50091593e-039,
       1.05633693e-052, 2.00783544e-067, 1.19583111e-083, 2.53516082e-101,
       2.13366994e-120, 7.82362256e-141, 1.35207589e-162, 1.17626639e-185,
       5.43900453e-210, 1.39669047e-235, 2.06134523e-262, 1.79365445e-290,
       9.36204992e-320, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

- 적분을 한번에 수행할 수 없으니까 순차적으로 적분을 해주는 코드가 필요

In [258]:
basic_data.iloc[0,1]+1

8501

In [259]:
integrate.quad(lambda x: beta.pdf(x, basic_data.iloc[0,2]+1,basic_data.iloc[0,1]-basic_data.iloc[0,2]+1)*\
               beta.cdf(x,basic_data.iloc[1,2]+1,basic_data.iloc[1,1]-basic_data.iloc[1,2]+1) , 0, 1)

(0.966554243344272, 2.7706948534619212e-09)

In [255]:
z = np.linspace(beta.ppf(0.01, 1, 1),beta.ppf(0.99, 1, 1), 100)

r = 0

def func_pdf(data, z,i,j): # 이게 r값
    return beta.pdf(z, data.iloc[i,2]+1, data.iloc[i,1] - data.iloc[i,2]+1)


def func_cdf(data, z,i,j):
    return beta.cdf(z, data.iloc[i,2]+1, data.iloc[i,1] - data.iloc[i,2]+1)

func_pdf(basic_data, z, 1,1)*func_cdf(basic_data,z, 1,1)

r = func_cdf(basic_data,z, 1,1)

r = r*func_cdf(basic_data,z, 0,1)

r = func_pdf(basic_data,z, 1,1)

integrate.quad(func_pdf(basic_data, z, ))

In [215]:
basic_data.iloc[1,1]

8500

In [268]:
f = lambda x, y : beta.pdf(x,basic_data.iloc[1,2]+1, basic_data.iloc[1,1] - basic_data.iloc[1,2]+1)\
               *beta.cdf(x,basic_data.iloc[0,2]+1, basic_data.iloc[0,1] - basic_data.iloc[0,2]+1)

In [272]:
integrate.dblquad(f,0,1, lambda x: 0, lambda x:1)

(0.03344575665791428, 5.450926853986515e-10)

In [265]:
f = lambda x: beta.pdf(x, 1410+1, 8500-1410+1)
a = 100
b = 50
# x = np.linspace(beta.ppf(0.01, a, b),beta.ppf(0.99, a, b), 50)
#list(map(lambda x: beta.pdf(x, 1410+1, 8500-1410+1),z))
integrate.quad(lambda x: beta.pdf(x,basic_data.iloc[1,2]+1, basic_data.iloc[1,1] - basic_data.iloc[1,2]+1)\
               *beta.cdf(x,basic_data.iloc[0,2]+1, basic_data.iloc[0,1] - basic_data.iloc[0,2]+1),0,1)


(0.03344575665791428, 5.450926853986515e-10)

In [140]:
#i가 1일때 j는 2에서 r값을 구하고, 3에서 구한 r값을 업데이트한다. 이 값을 가진 함수를 integrate

def bayesian_stat_for_rate(data):
    k = len(data)
#     print(k)
    for i in range(0,k):
        print(i)
        lst = list(range(0,k,1))
        set_lst = set(lst)
        index = list(set_lst-{i})

        #가능도 함수 구하는 함수
        lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
                               data.iloc[i,2]+1)
        
        integrate.quad(lambda x: beta.pdf(x, 1410+1, 8500-1410+1)*beta.cdf(x, 1500+1, 8500-1500+1),0,1)
#         global x
        
        for j in index:
#             lambda x: beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
#                                  data.iloc[j,2]+1)
            
#             print(result[i] = integrate.quad(lambda x : beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
#                                    data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
#                                  data.iloc[j,2]+1),0 ,1)[0])
            print(integrate.quad(lambda x : beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
                                   data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
                                 data.iloc[j,2]+1),0 ,1)[0])
            
            
            
#             result[i] = integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
#                                    data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
#                                  data.iloc[j,2]+1),0,1)[0]
#             print(integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - \
#                                    data.iloc[i,2]+1) * beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - \
#                                  data.iloc[j,2]+1),0,1)[0])
    
    return result


    #가능도 함수 f를 구해서 정의역 구간에서 integrate 하자 ==> likelihood의 적분 == 확률
#     result[i] = integrate.quad(funtion, 0,1)[0]
        
#     return result

In [141]:
bayesian_stat_for_rate(df_data)

0
0.966554243344272
0.9480853009068143
1
0.03344575665791428
0.4184502699376264
2
0.05191469909529321
0.5815497300606491


array([0, 0, 0])

In [72]:
df_data

group  trial  conversion
0     A   8500        1500
1     B   8500        1410
2     C   8500        1420

In [2]:
a = [1,2,3,4]
seta = set(a)

for i in range(1,5,1):
    print(seta-{i})

{2, 3, 4}
{1, 3, 4}
{1, 2, 4}
{1, 2, 3}


In [74]:
set_a

{1, 2, 3, 4}

In [82]:
from numpy.random import beta as beta_dist
import numpy as np

N_samp = 8500 # number of samples to draw
clicks_A = 1500 # insert your own data here
views_A = 8500
clicks_B = 1410 # ditto
views_B = 8500
alpha = 1.1 # just for the example - set your own!
beta_ = 14.2
A_samples = beta_dist(clicks_A+alpha, views_A-clicks_A+beta_, N_samp)
B_samples = beta_dist(clicks_B+alpha, views_B-clicks_B+beta_, N_samp)

In [83]:
np.mean(A_samples > B_samples)

0.9671764705882353

In [84]:
np.mean( 100.*(A_samples - B_samples)/B_samples > 3 )

0.8308235294117647

In [54]:
def bayesian_stat_for_rate(data):
    k = len(data)
    for i in range(1,k+1):
        lst = list(range(1,k+1))
        set_lst = set(lst)
        index = list(set_lst-{i})
        f = lambda(x : beta.pdf(data.iloc[i, 2]+1, beta.pdf(data.iloc[i,1] - data.iloc[i,2]+1)))
        for j in range(index):
            r = lambda(y : beta.cdf(data.iloc[j, 2]+1, beta.cdf(data.ilco[j,1] - data.iloc[j,2]+1)))
            
        result[i] = integrate(f,0,1)
        
    return result

In [55]:
bayesian_stat_for_rate([1,2,3,4,5])

{2, 3, 4, 5}
{1, 3, 4, 5}
{1, 2, 4, 5}
{1, 2, 3, 5}
{1, 2, 3, 4}


In [ ]:
dbeta = beta.pdf()
pbeta = beta.cdf()
integrate.quad(f, 0,1)

In [ ]:
# dbeta ==> beta.pdf (density function)
# pbeta ==> beta.rvs
# dbeta gives the density, pbeta the distribution function, 

In [23]:
conversion_a = 3300
conversion_b = 170

total_a = 10000
total_b = 500

prob_A_better_B = np.multiply(beta.rvs(1+conversion_a, 1+total_a-conversion_a, size=1),\
                              beta.rvs(1+conversion_b, 1+total_b-conversion_b))

prob_A_better_B

# f= lambda x:exp(-x**2)
# i = scipy.integrate.quad(f, 0, 1)

array([0.12231251])

In [216]:
# f = np.multiply(beta.rvs(1+conversion_a, 1+total_a-conversion_a, size=1),\
#                               beta.rvs(1+conversion_b, 1+total_b-conversion_b))
# i = integrate.quad(f, 0, 1)
# result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)

integrate.quad(lambda x,y : beta.pdf(1+conversion_a, 1+total_a-conversion_a, size=1),\
                              beta.pdf(1+conversion_b, 1+total_b-conversion_b), 0,1)

NameError: name 'conversion_b' is not defined

In [16]:
f= lambda x:np.exp(-x**2)
i = integrate.quad(f, 0, 1)

In [19]:
i

(0.7468241328124271, 8.291413475940725e-15)

In [1]:
import numpy as np
from math import lgamma
from numba import jit

#defining the functions used
@jit
def h(a, b, c, d):
    num = lgamma(a + c) + lgamma(b + d) + lgamma(a + b) + lgamma(c + d)
    den = lgamma(a) + lgamma(b) + lgamma(c) + lgamma(d) + lgamma(a + b + c + d)
    return np.exp(num - den)

@jit
def g0(a, b, c):    
    return np.exp(lgamma(a + b) + lgamma(a + c) - (lgamma(a + b + c) + lgamma(a)))

@jit
def hiter(a, b, c, d):
    while d > 1:
        d -= 1
        yield h(a, b, c, d) / d

def g(a, b, c, d):
    return g0(a, b, c) + sum(hiter(a, b, c, d))

def calc_prob_between(beta1, beta2):
    return g(beta1.args[0], beta1.args[1], beta2.args[0], beta2.args[1])

In [4]:
from scipy.stats import beta
import numpy as np
from numba import jit
from math import lgamma

#This is the known data: imporessions and conversions for the Control and Test set
imps_ctrl,convs_ctrl= 8500, 1410 
imps_test, convs_test= 8500, 1500

#here we create the Beta functions for the two sets
a_C, b_C = convs_ctrl+1, imps_ctrl-convs_ctrl+1
beta_C = beta(a_C, b_C)
a_T, b_T = convs_test+1, imps_test-convs_test+1
beta_T = beta(a_T, b_T)

#calculating the lift
lift=(beta_T.mean()-beta_C.mean())/beta_C.mean()

# #calculating the probability for Test to be better than Control
prob=calc_prob_between(beta_T, beta_C)

print (f"Test option lift Conversion Rates by {lift*100:2.2f}% with {prob*100:2.1f}% probability.")

Test option lift Conversion Rates by 6.38% with 96.7% probability.


In [6]:
print(beta_T.args[0], beta_T.args[1])

1501 7001


### 연속적분하는 Full code구현

In [376]:
# 연속적분을 어떻게 구현할까???
def sample(data):
    k = len(data)
    list_of_k = list(range(0,k,1))
    result = []
    for i in list_of_k:
        set_of_k = set(list_of_k)
        index = set_of_k-{i}
        result.append(0) # making space for results
        for j in index :
            print('i :',i, '   j :',j)
            result[i] = integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - data.iloc[i,2]+1)*\
                             beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - data.iloc[j,2]+1),0,1)[0]
    return result
sample(basic_data)

i : 0    j : 1
i : 1    j : 0


[0.966554243344272, 0.03344575665791428]

In [375]:
df_data

group  trial  conversion
0     A   8500        1500
1     B   8500        1410
2     C   8500        1420

0.02840740 0.92391007 0.04768253

In [377]:
def sample(data):
    k = len(data)
    list_of_k = list(range(0,k,1))
    result = []
    for i in list_of_k:
        set_of_k = set(list_of_k)
        index = set_of_k-{i}
        result.append(0) # making space for results
        for j in index :
            print('i :',i, '   j :',j)
#             result[i] = integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - data.iloc[i,2]+1)*\
#                              beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - data.iloc[j,2]+1),0,1)[0]
            print(integrate.quad(lambda x: beta.pdf(x, data.iloc[i,2]+1, data.iloc[i,1] - data.iloc[i,2]+1)*\
                              beta.cdf(x, data.iloc[j,2]+1, data.iloc[j,1] - data.iloc[j,2]+1),0,1))
    return result
sample(df_data)

i : 0    j : 1
(0.966554243344272, 2.7706948534619212e-09)
i : 0    j : 2
(0.9480853009068143, 2.3511395926944373e-09)
i : 1    j : 0
(0.03344575665791428, 5.450926853986515e-10)
i : 1    j : 2
(0.4184502699376264, 1.2427553859049198e-10)
i : 2    j : 0
(0.05191469909529321, 5.799861402776274e-10)
i : 2    j : 1
(0.5815497300606491, 4.202930388816484e-11)


[0, 0, 0]